package br.edu.unifei.ecot13.oni;

public enum PositiveTraitEnum implements TraitEnum {
	ANCIENT_KNOWLEDGE,
	ANIMAL_LOVER,
	BUFF,
	CAREGIVER,
	CHARISMATIC,
	DIVERS_LUNGS,
	DURESS_TO_IMPRESS,
	EARLY_BIRD,
	GERM_RESISTENCE,
	GOURMET,
	GREASE_MONKEY,
	GREEN_THUMB,
	HANDY,
	INNATELY_STYLISH,
	INTERIOR_DECORATOR,
	IRON_GUT,
	MOLE_HANDS,
	NIGHT_OWL,
	QUICK_LEARNER,
	SHRIVELLERD_TASTEBUDS,
	TWINKLETOES,
	UNCULTURED;
}
